/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicWebhooksProviderRouteImport } from './routes/api/public/webhooks/$provider'
import { Route as ApiPublicLicenseCheckRouteImport } from './routes/api/public/license/check'
import { Route as ApiPublicHooksBackupRouteImport } from './routes/api/public/hooks/backup'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhooksProviderRoute =
  ApiPublicWebhooksProviderRouteImport.update({
    id: '/api/public/webhooks/$provider',
    path: '/api/public/webhooks/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLicenseCheckRoute = ApiPublicLicenseCheckRouteImport.update({
  id: '/api/public/license/check',
  path: '/api/public/license/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackupRoute = ApiPublicHooksBackupRouteImport.update({
  id: '/api/public/hooks/backup',
  path: '/api/public/hooks/backup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
  '/api/public/license/check': typeof ApiPublicLicenseCheckRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
  '/api/public/license/check': typeof ApiPublicLicenseCheckRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/hooks/backup': typeof ApiPublicHooksBackupRoute
  '/api/public/license/check': typeof ApiPublicLicenseCheckRoute
  '/api/public/webhooks/$provider': typeof ApiPublicWebhooksProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/api/public/hooks/backup'
    | '/api/public/license/check'
    | '/api/public/webhooks/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/admin'
    | '/change-password'
    | '/dashboard'
    | '/api/public/hooks/backup'
    | '/api/public/license/check'
    | '/api/public/webhooks/$provider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/api/public/hooks/backup'
    | '/api/public/license/check'
    | '/api/public/webhooks/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksBackupRoute: typeof ApiPublicHooksBackupRoute
  ApiPublicLicenseCheckRoute: typeof ApiPublicLicenseCheckRoute
  ApiPublicWebhooksProviderRoute: typeof ApiPublicWebhooksProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhooks/$provider': {
      id: '/api/public/webhooks/$provider'
      path: '/api/public/webhooks/$provider'
      fullPath: '/api/public/webhooks/$provider'
      preLoaderRoute: typeof ApiPublicWebhooksProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/license/check': {
      id: '/api/public/license/check'
      path: '/api/public/license/check'
      fullPath: '/api/public/license/check'
      preLoaderRoute: typeof ApiPublicLicenseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backup': {
      id: '/api/public/hooks/backup'
      path: '/api/public/hooks/backup'
      fullPath: '/api/public/hooks/backup'
      preLoaderRoute: typeof ApiPublicHooksBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksBackupRoute: ApiPublicHooksBackupRoute,
  ApiPublicLicenseCheckRoute: ApiPublicLicenseCheckRoute,
  ApiPublicWebhooksProviderRoute: ApiPublicWebhooksProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
